before_script:
  - export VERSION=${CI_COMMIT_SHORT_SHA}
stages:
  - build
  - deploy_alpha
  - deploy_beta
  - deploy_prod
variables:
  GIT_STRATEGY: clone

Build:
  stage: build
  variables:
    image_biz_version: v1.0.0
  tags:
    - nvwa
  script:
    - sudo bash sh/build.sh $image_biz_version $CI_JOB_ID
    - echo ${image_biz_version}_Build${CI_JOB_ID} > image_version.conf
  artifacts:
    expire_in: 1 day
    paths:
      - image_version.conf
  when: always

DeployAlpha:
  stage: deploy_alpha
  before_script:
    - img_ver=$(cat image_version.conf)
  tags:
    - nvwa
  dependencies:
    - Build
  script:
    - sudo kubectl -n alpha-spot  --kubeconfig /root/.kube/alpha-k8s set image deployment/spot-en-api-reference spot-en-api-reference=harbor.matrixport.dev/spot/api-reference:${img_ver}
  when: manual

DeployAwsTest:
  stage: deploy_beta
  before_script:
    - img_ver=$(cat image_version.conf)
  tags:
    - nvwa-prod-cd
  dependencies:
    - Build
  script:
    - kubectl -n beta  --kubeconfig /root/.kube/nvwa-k8s set image deployment/spot-en-api-reference spot-en-api-reference=harbor.mark1.dev/spot/api-reference:${img_ver}
    - sudo /usr/local/bin/aws cloudfront create-invalidation --distribution-id EHN7BNKCMORTK --paths "/*"
  when: manual

# DeployProdBlocktrade:
#   stage: deploy_prod
#   before_script:
#     - img_ver=$(cat image_version.conf)
#   tags:
#     - nvwa-prod-cd
#   dependencies:
#     - Build
#   script:
#     - kubectl -n prod  --kubeconfig /root/.kube/prod-nvwa set image deployment/spot-Blocktrade-reference spot-Blocktrade-reference=harbor.mark1.dev/nvwa/api-reference:${img_ver}
#     #- sudo /usr/local/bin/aws cloudfront create-invalidation --distribution-id E2IK9I0S56WJMK --paths "/*"
#   when: manual


# DeployPreBlocktrade :
#   stage: deploy_pre
#   before_script:
#     - img_ver=$(cat image_version.conf)
#   tags:
#     - nvwa-prod-cd
#   dependencies:
#     - Build
#   script:
#     - kubectl -n pre  --kubeconfig /root/.kube/prod-nvwa set image deployment/spot-Blocktrade-reference spot-Blocktrade-reference=harbor.mark1.dev/nvwa/api-reference:${img_ver}
#     #- sudo /usr/local/bin/aws cloudfront create-invalidation --distribution-id E2IK9I0S56WJMK --paths "/*"
#   when: manual


DeployProd:
  stage: deploy_prod
  before_script:
    - img_ver=$(cat image_version.conf)
  tags:
    - nvwa-prod-cd
  dependencies:
    - Build
  script:
    - kubectl -n prod  --kubeconfig /root/.kube/prod-nvwa set image deployment/spot-en-api-reference spot-en-api-reference=harbor.mark1.dev/spot/api-reference:${img_ver}
    #- sudo /usr/local/bin/aws cloudfront create-invalidation --distribution-id E2IK9I0S56WJMK --paths "/*"
  when: manual
